- name: install mysql
  hosts: Web
  become: yes
  tasks:
  - name: mysql installation
    ansible.builtin.package:
      name: mysql
      state: present
  - name: mysql service start
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes
