- name: data-types 
  hosts: web
  vars:
    country: "Singapore is the best counry"  #string
    time: 4 # number
    places:  #list
      - queenstown
      - tampines
      - jurngeast
      - kranji
    current: true #boolen
    locations: #map
      tampies: hub
      queenstown: MRT
      kranji: baxter
  tasks:
  - name: about singapore
    ansible.builtin.debug:
      msg: "{{ country }} total {{ time }}, {{ places }} {{ current }}, {{ locations }}"
    
