- name: nginx script
  hosts: web
  become: yes
  tasks:
  - name: nginx install
    ansible.builtin.package:
    - name: nginx
      state: present
  - name: enable nginx
    ansible.builtin.service:
    - name: nginx
      state: started
      enabled: yes