- name: installation on nginx
  hosts: web
  become: yes
  tasks:
  - name: settingup nginx
    ansible.builtin.package:
    - name: nginx
      state: present
  - name: service enabling
    ansible.builtin.service:
    - name: nginx
      state: started
      enabled: yes