- name: task vars setup
  hosts: web
  vars:
    USER: RamaKrishna
    AGE: 35
    GENDER: Male
  tasks:
  - name: task level vars
    vars:
      USER: LAVANYA
    ansible.builtin.debug:
      msg: "My name is {{ USER}}, age is {{ AGE }} and gender is {{ GENDER }}"
  
  - name: next task of vars
    ansible.builtin.debug:
      msg: "My name is {{ USER}}, age is {{ AGE }} and gender is {{ GENDER }}"
